# Generated by Django 4.1.7 on 2023-02-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(max_length=255)),
                ('worke_type', models.CharField(choices=[('YT', 'Youtube'), ('IM', 'Instagram'), ('OT', 'Other')], default='OT', max_length=2)),
            ],
        ),
    ]
